# Generated by Django 2.2.2 on 2019-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
    ]
