# Generated by Django 2.1.7 on 2019-07-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('django_basics', '0002_seo_meta_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={},
        ),
        migrations.AddField(
            model_name='seo',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='path',
            field=models.CharField(help_text='URL of place to override seo elements. E.g. /something/here', max_length=128),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='seo',
            unique_together={('path', 'site')},
        ),
    ]
