# Generated by Django 2.1.7 on 2019-07-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0003_auto_20190724_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEOs'},
        ),
    ]
