# Generated by Django 2.1.7 on 2019-07-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0004_auto_20190724_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='title',
        ),
    ]
