# Generated by Django 2.2.4 on 2019-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_basics', '0005_remove_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='link_href',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='seo',
            name='link_rel',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
